import { SystemProps } from '../../types';

export const extractSystemProps = (others: SystemProps) => {
  const {
    m,
    my,
    mx,
    mt,
    mb,
    mr,
    ml,
    p,
    py,
    px,
    pt,
    pb,
    pr,
    pl,
    bg,
    c,
    opacity,
    ff,
    fz,
    fw,
    lts,
    ta,
    lh,
    fs,
    tt,
    td,
    w,
    miw,
    maw,
    h,
    mih,
    mah,
    bgsz,
    bgp,
    bgr,
    bga,
    pos,
    top,
    left,
    bottom,
    right,
    inset,
    display,
    ...rest
  } = others;
  return {
    systemStyles: {
      marginTop: mt ?? my ?? m,
      marginBottom: mb ?? my ?? m,
      marginLeft: ml ?? mx ?? m,
      marginRight: mr ?? mx ?? m,
      paddingTop: pt ?? py ?? p,
      paddingBottom: pb ?? py ?? p,
      paddingLeft: pl ?? px ?? p,
      paddingRight: pr ?? px ?? p,
      background: bg,
      color: c,
      opacity,
      fontFamily: ff,
      fontSize: fz,
      fontWeight: fw,
      letterSpacing: lts,
      textAlign: ta,
      lineHeight: lh,
      fontStyle: fs,
      textTransform: tt,
      textDecoration: td,
      width: w,
      minWidth: miw,
      maxWidth: maw,
      height: h,
      minHeight: mih,
      maxHeight: mah,
      backgroundSize: bgsz,
      backgroundPosition: bgp,
      backgroundRepeat: bgr,
      backgroundAttachment: bga,
      position: pos,
      top,
      left,
      bottom,
      right,
      inset,
      display,
    },
    rest,
  };
};
